use w5base;
create table timeplan (
  id         bigint(20) NOT NULL,
  name       varchar(60) NOT NULL,
  cistatus   int(2)      NOT NULL,
  mandator   bigint(20)  default NULL,
    adm             bigint(20)  default NULL,
    adm2            bigint(20)  default NULL,
    tmode           varchar(80) default NULL, 
    visiblemode     int(1)      default '0',
    description     longtext    default NULL,
    additional      longtext    default NULL,
    data            longtext    default NULL,
    defstarthour    int(2)      default '0',
    defendhour      int(2)      default '24',
    prnapprovedline varchar(128) default NULL,
    lineheight      varchar(10) default 'auto',
    vbarcolor       varchar(20) default 'blue',
  comments    longtext     default NULL,timezone varchar(40) default 'GMT ',
  createdate datetime NOT NULL default '0000-00-00 00:00:00',
  modifydate datetime NOT NULL default '0000-00-00 00:00:00',
  createuser bigint(20) default NULL,
  modifyuser bigint(20) default NULL,
  editor     varchar(100) NOT NULL default '',
  realeditor varchar(100) NOT NULL default '',
  srcsys     varchar(10) default 'w5base',
  srcid      varchar(20) default NULL,
  srcload    datetime    default NULL,
  PRIMARY KEY  (id),
  key(tmode),
  UNIQUE KEY name (name),KEY(mandator),
  UNIQUE KEY `srcsys` (srcsys,srcid)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
create table tspanentry (
  id         bigint(20) NOT NULL,
  name varchar(40) default NULL,
   tfrom         datetime    NOT NULL default '0000-00-00 00:00:00',
   tto           datetime    default NULL,
   timeplanref   bigint(20)  NOT NULL     comment 'id of timeplan',
   useridref     bigint(20)  default NULL comment 'id of user, if personplan',
   grpidref      bigint(20)  default NULL comment 'id of grp, if groupplan',
   cigrpidref    bigint(20)  default NULL comment 'id of mgmtitemgroup',
   locidref      bigint(20)  default NULL comment 'id of location',
   dataref       varchar(20) default NULL comment 'data name, if resurceplan',
   subsys        varchar(40) default NULL comment 'calendar module',
   entrytyp      char(20)    default NULL comment 'usage depend on subsys',
   cistatus      int(2)      NOT NULL     comment 'usage depend on subsys',
   comments      longtext    default NULL,
   additional    longtext    default NULL comment 'usage depend on subsys',
  createdate datetime NOT NULL default '0000-00-00 00:00:00',
  modifydate datetime NOT NULL default '0000-00-00 00:00:00',
  createuser bigint(20) NOT NULL default '0',
  modifyuser bigint(20) NOT NULL default '0',
  editor     varchar(100) NOT NULL default '',
  realeditor varchar(100) NOT NULL default '',
  srcsys     varchar(10) default 'w5base',
  srcid      varchar(20) default NULL,
  srcload    datetime    default NULL,
  PRIMARY KEY  (id),
  KEY s1 (tfrom),key userid (useridref), key s2 (tto),
  key(name),key(timeplanref),
  UNIQUE KEY tfrom (tfrom,entrytyp,useridref,timeplanref,subsys),
  UNIQUE KEY span  (tfrom,tto,dataref,useridref,timeplanref,subsys),
  UNIQUE KEY `srcsys` (srcsys,srcid),key (useridref),
  FOREIGN KEY (timeplanref) REFERENCES timeplan (id) ON DELETE CASCADE,
  FOREIGN KEY (grpidref) REFERENCES grp (grpid) ON DELETE CASCADE,
  FOREIGN KEY (cigrpidref) REFERENCES mgmtitemgroup (id) ON DELETE CASCADE,
  FOREIGN KEY (locidref) REFERENCES location (id) ON DELETE CASCADE,
  FOREIGN KEY (useridref) REFERENCES contact (userid) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE tsrange (
  tspanentryid bigint(20) NOT NULL,
  s datetime default NULL,
  m datetime default NULL,
  e datetime default NULL,
  timeplanref bigint(20),
  KEY timeplanref (timeplanref),
  key startonly(s),
  key endonly(e),
  key middle(m),
  FOREIGN KEY (tspanentryid) REFERENCES tspanentry (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
