# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-MyServer
version:      0.41
version_from: lib/DBIx/MyServer.pm
installdirs:  site
requires:
    DBD::mysql:                    0.00
    DBI:                           0.00
    Digest::SHA1:                  0.00

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
