use w5base;
create table PAT_businessseg(
  id              bigint(20)   NOT NULL,
  name            varchar(32)  NOT NULL,
  title           varchar(254) NOT NULL,
  bsegopt         varchar(254) NOT NULL,
  sopt            varchar(254) NOT NULL,
  orgname         varchar(254) NOT NULL,
  orgshort        varchar(32)  NOT NULL,
   additional     longtext     default NULL,
  comments    longtext     default NULL,
  createdate datetime NOT NULL default '0000-00-00 00:00:00',
  modifydate datetime NOT NULL default '0000-00-00 00:00:00',
  createuser bigint(20) default NULL,
  modifyuser bigint(20) default NULL,
  editor     varchar(100) NOT NULL default '',
  realeditor varchar(100) NOT NULL default '',
  srcsys     varchar(100) default 'w5base',
  srcid      varchar(20) default NULL,
  srcload    datetime    default NULL,
  UNIQUE KEY `srcsys` (srcsys,srcid),
  PRIMARY KEY  (id),
  unique(name),
  key(title)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
create table PAT_subprocess(
  id              bigint(20)   NOT NULL,
  name            varchar(32)  NOT NULL,
  title           varchar(254) NOT NULL,
  businessseg     bigint(20)   NOT NULL,
  business        varchar(32)  NOT NULL,
  onlinetime      text,
  usetime         text,
  coretime        text,
  ibi_nonprodtime text,
  ibi_th_nonprodtime_monfri int(20) default NULL,
  ibi_th_nonprodtime_sat    int(20) default NULL,
  ibi_th_nonprodtime_sun    int(20) default NULL,
  ibi_coretime    text,
  ibi_th_coretime_monfri    int(20) default NULL,
  ibi_th_coretime_sat       int(20) default NULL,
  ibi_th_coretime_sun       int(20) default NULL,
   additional     longtext     default NULL,
  comments    longtext     default NULL,description longtext,
  createdate datetime NOT NULL default '0000-00-00 00:00:00',
  modifydate datetime NOT NULL default '0000-00-00 00:00:00',
  createuser bigint(20) default NULL,
  modifyuser bigint(20) default NULL,
  editor     varchar(100) NOT NULL default '',
  realeditor varchar(100) NOT NULL default '',
  srcsys     varchar(100) default 'w5base',
  srcid      varchar(20) default NULL,
  srcload    datetime    default NULL,
  UNIQUE KEY `srcsys` (srcsys,srcid),
  PRIMARY KEY  (id),
  unique(name),
  FOREIGN KEY fk_bsseg (businessseg)  
  REFERENCES PAT_businessseg (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
create table PAT_ictname(
  id              bigint(20)   NOT NULL,
  name            varchar(64)  NOT NULL,
  ictoid          varchar(32),
   additional     longtext     default NULL,
  comments    longtext     default NULL,
  createdate datetime NOT NULL default '0000-00-00 00:00:00',
  modifydate datetime NOT NULL default '0000-00-00 00:00:00',
  createuser bigint(20) default NULL,
  modifyuser bigint(20) default NULL,
  editor     varchar(100) NOT NULL default '',
  realeditor varchar(100) NOT NULL default '',
  srcsys     varchar(100) default 'w5base',
  srcid      varchar(20) default NULL,
  srcload    datetime    default NULL,
  UNIQUE KEY `srcsys` (srcsys,srcid),
  PRIMARY KEY  (id),
  unique(name),
  key(ictoid)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
create table PAT_lnksubprocessictname(
  id              bigint(20)   NOT NULL,
  subprocess      bigint(20)   NOT NULL,
  ictname         bigint(20)   NOT NULL,
  relevance       tinyint unsigned not NULL default '1',
   additional     longtext     default NULL,
  comments    longtext     default NULL,
  createdate datetime NOT NULL default '0000-00-00 00:00:00',
  modifydate datetime NOT NULL default '0000-00-00 00:00:00',
  createuser bigint(20) default NULL,
  modifyuser bigint(20) default NULL,
  editor     varchar(100) NOT NULL default '',
  realeditor varchar(100) NOT NULL default '',
  srcsys     varchar(100) default 'w5base',
  srcid      varchar(20) default NULL,
  srcload    datetime    default NULL,
  UNIQUE KEY `srcsys` (srcsys,srcid),
  PRIMARY KEY  (id),
  unique(subprocess,ictname),
  FOREIGN KEY fk_subprocess (subprocess)  
  REFERENCES PAT_subprocess (id) ON DELETE CASCADE,
  FOREIGN KEY fk_ictname (ictname)  
  REFERENCES PAT_ictname (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
