use w5base;
create table tsotc_sysreq (
  id           bigint(20)  NOT NULL,
  aliassysname varchar(40) NOT NULL,
  appl         bigint(20)  NOT NULL,
  applname     varchar(40) NOT NULL,
  reqstatus    int(2)      NOT NULL,  
  opmode       varchar(20) default NULL,
  systemclass  varchar(20) default NULL,
  cpucount     int(20)     default NULL,
  memory       int(20)     default NULL,
  osrelease    varchar(40) default NULL,
  comments     longtext    default NULL,
  otcsystemid  varchar(40) default NULL,
  otcdepldate  datetime NOT NULL default '0000-00-00 00:00:00',
  createdate datetime NOT NULL default '0000-00-00 00:00:00',
  modifydate datetime NOT NULL default '0000-00-00 00:00:00',
  createuser bigint(20)   default NULL,
  modifyuser bigint(20)   default NULL,
  editor     varchar(100) NOT NULL default '',
  realeditor varchar(100) NOT NULL default '',
  srcsys     varchar(100) default 'w5base',
  srcid      varchar(20)  default NULL,
  srcload    datetime     default NULL,
  PRIMARY KEY  (id),
  UNIQUE KEY `srcsys` (srcsys,srcid)
)  ENGINE=MyISAM DEFAULT CHARSET=latin1;
create table tsotc_sysreq_fs (
  id           bigint(20)  NOT NULL,
  sysreq       bigint(20)  NOT NULL,
  fsentry      varchar(128) NOT NULL,
  fssize       bigint(20),
  comments    longtext    default NULL,
  createdate datetime NOT NULL default '0000-00-00 00:00:00',
  modifydate datetime NOT NULL default '0000-00-00 00:00:00',
  createuser bigint(20)   default NULL,
  modifyuser bigint(20)   default NULL,
  editor     varchar(100) NOT NULL default '',
  realeditor varchar(100) NOT NULL default '',
  srcsys     varchar(100) default 'w5base',
  srcid      varchar(20)  default NULL,
  srcload    datetime     default NULL,
  PRIMARY KEY  (id),
  FOREIGN KEY fk_tsotc_sysreq_fs1 (sysreq) 
  REFERENCES tsotc_sysreq (id) ON DELETE CASCADE,
  UNIQUE KEY `srcsys` (srcsys,srcid)
)  ENGINE=MyISAM DEFAULT CHARSET=latin1;
