#!/usr/bin/perl
use lib qw(/opt/w5base2/lib /opt/w5base/lib);
use strict;                   
use W5Base::API;
use Data::Dumper;

my $DefaultInitfileName=".W5Base.Interface";
my $DefaultBase="https://w5base.net/w5base/auth/";
my ($help,$verbose,$store,$loginuser,$loginpass,$quiet,$base,$lang,$initfile);
my %P=("help"=>\$help,"base=s"=>\$base,"lang=s"=>\$lang,
       "webuser=s"=>\$loginuser,"webpass=s"=> \$loginpass,
       "verbose+"=>\$verbose);
my $optresult=XGetOptions(\%P,\&Help,undef,undef,$DefaultInitfileName);

#######################################################################
# create connection config
#
my $apidebug=$verbose>=3 ? 1 : 0;
my $Config=createConfig($base,$loginuser,$loginpass,$lang,$apidebug);
if (!defined($Config)){
   msg(ERROR,"base url or username/password is not valid");exit(1);
}
else{
   msg(DEBUG,"create of config ok");
}
msg(DEBUG,"verbose=$verbose");


#######################################################################
# load ModuleObject
#
my $objectname="base::workflow";
my $wf=getModuleObject($Config,$objectname);
if (!defined($wf)){
   msg(ERROR,"can't load object $objectname");exit(2);
}
else{
   msg(DEBUG,"create of ModuleObject $wf ok");
}

my $WfRec={ class=>'AL_TCom::workflow::businesreq',
            name=>'Hallo Welt 1',
            reqnature=>'undef',
            detaildescription=>"Dies ist der lange Text\n".
                               "mit mehreren Zeilen",
            affectedapplication=>'W5Base/Darwin',
            affectedapplication=>'ADS_WIRK',
            reqdesdate=>'in 2 weeks',
            extdesc_desstart=>'2003-01-01 14:00:00',
            extdesc_desend=>'2004-01-01 14:00:00',
            customerrefno=>'11223344'
          };

#######################################################################
#
msg(INFO,"create Workflow");
if (my $id=$wf->storeRecord($WfRec)){
   msg(INFO,"ok newid=$id");
   $wf->SetFilter({id=>[$id]});
   foreach my $WfRec ($wf->getHashList(qw(id name posibleactions shortactionlog
                                          step class))){
      printf("WfRec=%s\n",Dumper($WfRec));
      my $id=$wf->storeRecord({note=>'Hallo Welt',
                               extdesc_dependencies=>"Dies ist Z1\nDies ist2\n",                               
                               action=>'wffollowup'},$WfRec->{id});

   }
   $wf->dieOnERROR();
   exit(0);
}
else{
   $wf->dieOnERROR();
}
exit(1);

#######################################################################
sub Help
{
   print(<<EOF);
$RealScript [options] FullnameFilter

   --verbose  display more details of operation process
   --quiet    only errors would be displayed
   --base     base url of filemgmt (default: $DefaultBase)

   --webuser  username
   --webpass  password
   --store    stores the parameters (not help,verbose and store)
   --initfile use a specific initfile (default: $DefaultInitfileName)
   --help     show this help

EOF
}
#######################################################################
exit(255);
