#!/usr/bin/perl
use lib qw(/opt/w5base2/lib /opt/w5base/lib);
use strict;                   
use W5Base::API;
use W5Kernel;

my $DefaultBase="https://w5base.net/w5base/auth/";
my ($help,$verbose,$loginuser,$loginpass,$quiet,$base,$lang);
my %P=("help"=>\$help,"base=s"=>\$base,"lang=s"=>\$lang,
       "webuser=s"=>\$loginuser,"webpass=s"=> \$loginpass,
       "verbose+"=>\$verbose);
my $optresult=XGetOptions(\%P,\&Help,undef,undef,".W5Base.Interface");

#######################################################################
# create connection config
#
my $apidebug=$verbose>=3 ? 1 : 0;
my $Config=createConfig($base,$loginuser,$loginpass,$lang,$apidebug);
if (!defined($Config)){
   msg(ERROR,"base or username/password is not valid");exit(1);
}
else{
   msg(DEBUG,"create of config ok");
}
msg(DEBUG,"verbose=$verbose");


my $flt=$ARGV[0];
if ($flt eq ""){
   msg(ERROR,"no filter specified");exit(3);
}
msg(INFO,"flt='$flt'");



#######################################################################
# load ModuleObject
#
my $objectname="itil::lnkapplappl";
my $lnk=getModuleObject($Config,$objectname);
if (!defined($lnk)){
   msg(ERROR,"can't load object $objectname");exit(2);
}
else{
   msg(DEBUG,"create of ModuleObject $lnk ok");
}


#######################################################################
# do search
#
$lnk->SetFilter({fromappl=>$flt,toapplcistatus=>4,cistatusid=>4});
my $st=0;
my $blk=5;
my @l;
do{
   $lnk->Limit($st+$blk,$st);
   if (@l=$lnk->getHashList(qw(toappl contype rawcontype))){
      if ($#l==-1){
         msg(INFO,"no data found in $objectname matching fullname=$flt");
         exit(2);
      }
      else{
         foreach my $rec (@l){
             printf("%s\n", UTF8toLatin1($rec->{toappl}));
             printf("%s\n", UTF8toLatin1($rec->{contype}));
             printf("%s\n", UTF8toLatin1($rec->{rawcontype}));
             printf("\n");
         }
      }
   }
   $st+=$blk;
}while($#l==$blk-1);
$lnk->dieOnERROR();
exit(0);

#######################################################################
sub Help
{
   print(<<EOF);
$RealScript [options] FullnameFilter

   --verbose display more details of operation process
   --quiet   only errors would be displayed
   --base    base url of filemgmt (default: $DefaultBase)

   --webuser username
   --webpass password
   --store   stores the parameters (not help,verbose and store)
   --help    show this help

EOF
}
#######################################################################
exit(255);
