#!/usr/bin/perl
use lib qw(/opt/w5base2/lib /opt/w5base/lib);
use strict;                   
use W5Base::API;

my $DefaultBase="https://w5base.net/w5base/auth/";
my ($help,$verbose,$loginuser,$loginpass,$quiet,$base);
my %P=("help"=>\$help,"base=s"=>\$base,
       "webuser=s"=>\$loginuser,"webpass=s"=> \$loginpass,
       "verbose+"=>\$verbose);
my $optresult=XGetOptions(\%P,\&Help,undef,undef,".W5Base.Interface");

#######################################################################
my $Config=createConfig($base,$loginuser,$loginpass);
if (!defined($Config)){
   msg(ERROR,"base or username/password is not valid");exit(1);
}
else{
   msg(DEBUG,"create of config ok");
}

my $objectname="base::user";
my $user=getModuleObject($Config,$objectname);
if (!defined($user)){
   msg(ERROR,"can't load object $objectname");exit(2);
}
else{
   msg(DEBUG,"create of ModuleObject $user ok");
}

my $flt=$ARGV[0];
if ($flt eq ""){
   msg(ERROR,"no filter specified");exit(3);
}

$user->SetFilter({fullname=>$flt});
my @l=$user->getHashList(qw(fullname surname accounts));
if ($#l==-1){
   msg(INFO,"no data found in $objectname matching fullname=$flt");exit(2);
}
else{
   foreach my $rec (@l){
       printf("$rec->{fullname}\n");
       foreach my $arec (@{$rec->{accounts}}){
          printf(" - $arec->{account}\n");
       }
   }
}
exit(1);

#######################################################################
sub Help
{
   print(<<EOF);
$RealScript [options] FullnameFilter

   --verbose display more details of operation process
   --quiet   only errors would be displayed
   --base    base url of filemgmt (default: $DefaultBase)
   --out     output file to store the xml response (default: STDOUT)

   --webuser username
   --webpass password
   --store   stores the parameters (not help,verbose and store)
   --help    show this help

EOF
}
#######################################################################
exit(255);
