#!/usr/bin/perl
use lib qw(/opt/w5base2/lib /opt/w5base/lib);
use strict;                   
use W5Base::API;
use W5Kernel;
use Data::Dumper;

my $DefaultBase="https://w5base.net/w5base/auth/";
my ($help,$verbose,$loginuser,$loginpass,$quiet,$base,$lang);
my %P=("help"=>\$help,"base=s"=>\$base,"lang=s"=>\$lang,
       "webuser=s"=>\$loginuser,"webpass=s"=> \$loginpass,
       "verbose+"=>\$verbose);
my $optresult=XGetOptions(\%P,\&Help,undef,undef,".W5Base.Interface");

#######################################################################
# create connection config
#
my $apidebug=$verbose>=3 ? 1 : 0;
my $Config=createConfig($base,$loginuser,$loginpass,$lang,$apidebug);
if (!defined($Config)){
   msg(ERROR,"base or username/password is not valid");exit(1);
}
else{
   msg(DEBUG,"create of config ok");
}
msg(DEBUG,"verbose=$verbose");

#######################################################################
# load ModuleObject
#
my $objectname="AL_TCom::swinstance";
my $i=getModuleObject($Config,$objectname);
if (!defined($i)){
   msg(ERROR,"can't load object $objectname");exit(2);
}
else{
   msg(DEBUG,"create of ModuleObject $i ok");
}


my $objectname="AL_TCom::system";
my $s=getModuleObject($Config,$objectname);
if (!defined($s)){
   msg(ERROR,"can't load object $objectname");exit(2);
}
else{
   msg(DEBUG,"create of ModuleObject $s ok");
}

#######################################################################
# do search
#
$i->SetFilter({name=>"*W5*",cistatusid=>4,mandator=>'!Extern'});
my $st=0;
my $blk=5;
my @l;
do{
   $i->Limit($st+$blk,$st);
   if (@l=$i->getHashList(qw(fullname name systemid itclustsvcid swteam))){
      foreach my $rec (@l){
         printf STDERR ("Instance: $rec->{fullname}\n");
         if ($rec->{systemid} ne ""){
            $s->ResetFilter();
            $s->SetFilter({id=>$rec->{systemid}});
            if (my @sys=$s->getHashList(qw(name ipaddresses))){
               printf STDERR ("  Sys: $sys[0]->{name}\n");
               foreach my $iprec (@{$sys[0]->{ipaddresses}->{record}}){
                  printf STDERR ("   ip: $iprec->{name} ".
                                 "$iprec->{shortcomments}\n");
               }
               printf("\n");
            }
         }
      }
   }
   $st+=$blk;
}while($#l==$blk-1);
$i->dieOnERROR();
exit(0);

#######################################################################
sub Help
{
   print(<<EOF);
$RealScript [options] FullnameFilter

   --verbose display more details of operation process
   --quiet   only errors would be displayed
   --base    base url of filemgmt (default: $DefaultBase)

   --webuser username
   --webpass password
   --store   stores the parameters (not help,verbose and store)
   --help    show this help

EOF
}
#######################################################################
exit(255);
