#!/usr/bin/perl
use lib qw(/opt/w5base2/lib /opt/w5base/lib);
use strict;                   
use W5Base::API;
use Data::Dumper;

my $DefaultBase="https://w5base.net/w5base/auth/";
my ($help,$verbose,$loginuser,$loginpass,$quiet,$base,$lang);
my %P=("help"=>\$help,"base=s"=>\$base,"lang=s"=>\$lang,
       "webuser=s"=>\$loginuser,"webpass=s"=> \$loginpass,
       "verbose+"=>\$verbose);
my $optresult=XGetOptions(\%P,\&Help,undef,undef,".W5Base.Interface");

#######################################################################
# create connection config
#
my $apidebug=$verbose>=3 ? 1 : 0;
my $Config=createConfig($base,$loginuser,$loginpass,$lang,$apidebug);
if (!defined($Config)){
   msg(ERROR,"base url or username/password is not valid");exit(1);
}
else{
   msg(DEBUG,"create of config ok");
}
msg(DEBUG,"verbose=$verbose");


#######################################################################
# load ModuleObject
#
my $objectname="base::workflow";
my $wf=getModuleObject($Config,$objectname);
if (!defined($wf)){
   msg(ERROR,"can't load object $objectname");exit(2);
}
else{
   msg(DEBUG,"create of ModuleObject $wf ok");
}

$wf->SetFilter({id=>[13026090780001]});
foreach my $WfRec ($wf->getHashList(qw(name shortactionlog posibleactions id
                                       step class))){
   printf("WfRec=%s\n",Dumper($WfRec));
   my $id=$WfRec->{id};
   my $id=$wf->storeRecord({note=>'[chm.test]Hallo',
                            action=>'wfreject'},$id);
   $wf->dieOnERROR();
   msg(INFO,"fineproc done");

}
exit(0);

#######################################################################
sub Help
{
   print(<<EOF);
$RealScript [options] FullnameFilter

   --verbose display more details of operation process
   --quiet   only errors would be displayed
   --base    base url of filemgmt (default: $DefaultBase)

   --webuser username
   --webpass password
   --store   stores the parameters (not help,verbose and store)
   --help    show this help

EOF
}
#######################################################################
exit(255);
