#!/usr/bin/env perl 
#  W5Base Framework W5Replicate - object mirroring tool
#  Copyright (C) 2017  Hartmut Vogler (it@guru.de)
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
use FindBin;
use lib "$FindBin::Bin/../lib";
use lib "$FindBin::Bin/../mod";
use RPC::Smart::Client;
use strict;
use kernel;
use kernel::config;
use kernel::EventController;
use Getopt::Long;
use kernel::cgi;
use List::Util 'shuffle';
use File::Temp qw(tempdir);
use Time::HiRes qw(usleep sleep);
use DBI;
use POSIX;
use vars qw($opt_v $opt_h $opt_c $opt_t $opt_k $opt_f $opt_a
            $opt_q $opt_l $configname);
$|=1;
my $startProcessPPID=getppid(); # there is need to check ppid at at start 
                                # against current, because IO::Multiplex and
                                # DBD::Oracle modifies SIGPIPE Handler!

exit(1) if (!GetOptions('verbose'=>\$opt_v,
                        'tasks=i'=>\$opt_t,
                        'keycol=i'=>\$opt_k,
                        'quietmode'=>\$opt_q,
                        'force'=>\$opt_f,          # process if other sessions
                        'archive'=>\$opt_a,        # archive old records
                        'limittime=i'=>\$opt_l,
                        'debug'=>\$opt_v,
                        'help'=>\$opt_h,
                        'config=s'=>\$opt_c));
my @ObjectFilter=@ARGV;

if ($opt_q){
   open STDOUT, '>>/dev/null' or die "Can't write to /dev/null: $!";
}
if (!defined($opt_k)){
   $opt_k=0;                       # no key column handling
}
if (!defined($opt_a)){
   $opt_a=0;
}
else{
   $opt_a=1;
}
if ($opt_k<0 || $opt_k>100){
   msg(ERROR,"invalid key column '$opt_k'");
   exit(1);
}

if ($opt_k==0 &&  $opt_a==1){
   msg(ERROR,"record archiving only works in combination with key column");
   exit(1);
}


my $ReplicationStart=time();
if ($opt_h){
   Help();exit(255);
}
if ($opt_v){
   $W5V2::Debug=1;
}
else{
   $W5V2::Debug=0;
}



if ($ENV{REMOTE_USER} eq ""){
   if ($ENV{USER} ne ""){
      $ENV{REMOTE_USER}="system/$ENV{USER}";
   }
   else{
      $ENV{REMOTE_USER}="system/unknown";
   }
   $ENV{REAL_REMOTE_USER}="system/W5Replicate";
}
$W5V2::OperationContext="W5Replicate";


#
# handling option to set commandline specfied config-name
#
if ($opt_c eq ""){
   $opt_c="w5csv2db";
}
$configname=$opt_c;


sub doShutdown{  # doShutdown handling if CTRL+C is pressed on main process
   printf STDERR ("doShutdown started...\n");
   exit();
}


#$SIG{CHLD}='DEFAULT';  # signal, falls ein tocherprozess terminiert
#$SIG{HUP}=\&doShutdown;
$SIG{INT}=\&doShutdown;
#$SIG{KILL}=\&doShutdown;


my %ClientParam=();

my $config=new kernel::config();

if (!$config->readconfig("$FindBin::Bin/..",$configname)){
   msg(ERROR,"can't read configfile '%s'",$configname);
   exit(1);
}

sub getOracleDBIschemaInfo
{
   my $dbi=shift;
   my $schema=shift;

   return(@{$W5REPL::schemaInfoCache}) if (defined($W5REPL::schemaInfoCache));

   msg(INFO,"load schemaInfoCache in process $$");
   my $sth=$dbi->table_info(undef,$schema,'%');
   my $found=0;
   my @l=$sth->getHashList();

   $W5REPL::schemaInfoCache=\@l;

   return(@l);
}



#
# Connect to replication target oracle DB via DBI
#
sub getOracleDBIConnectionHandle
{
   my $dbconnect=$config->Param("ORACONNECT");
   my $dbuser=$config->Param("ORAUSER");
   my $dbpass=$config->Param("ORAPASS");
   msg(INFO,"try ora connect='$dbconnect' user='$dbuser'");

   if ($dbconnect eq "" || $dbuser eq "" || $dbpass eq ""){
      msg(ERROR,"fatal error - not enough connection informations");
      exit(255);
   }
   my $dst=DBI->connect($dbconnect,$dbuser,$dbpass,{
      AutoCommit=>0,
  #    FetchHashKeyName=>'NAME_lc',
      ora_action=>'W5csv2db'
   });
   if (!defined($dst)){
      msg(ERROR,$DBI::errstr);
      sleep(20);
      exit(100);
   }
   $dst->{'LongTruncOk'} = 1;
   $dst->{'LongReadLen'} = 128000;
   $dst->doCmd("alter session set NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS'");
   $dst->doCmd("alter session set NLS_NUMERIC_CHARACTERS='. '");
   $dst->doCmd("alter session set TIME_ZONE='GMT'");
   # set session TIME_ZONE to GMT to ensure to get a GMT timestamp
   # while using CURRENT_DATE. Note: There is not way to ensure to get
   # a GMT timestamp in SYSDATE on session level (SYSDATE timezone can
   # only be set from system root! (not the DBA!))
   msg(INFO,"connect to replication target '$dbconnect' successfull");
   return($dst,uc($dbuser),lc($dbuser).'@'.lc($dbconnect));
}

#create table tcsv (
#   W5RAWLINE varchar2(4000),
#   W5KEY     varchar2(20),
#   W5MDATE   DATE not null,
#   W5ISDEL   char(1) default '0'
#);
#create index tcsvi1 on tcsv (W5RAWLINE);
#create index tcsvi2 on tcsv (W5MDATE);
#create index tcsvi3 on tcsv (W5ISDEL);


#
# find system commandos sort, comm and diff
#
my @SYSCMD=qw(sort comm diff cat sftp uniq dd);
my %SYSCMD;
foreach my $dir (split(":",$ENV{PATH})){
   $dir.="/" if (!($dir=~m/\/$/));
   foreach my $cmd (@SYSCMD){
      $SYSCMD{$cmd}=$dir.$cmd if (!exists($SYSCMD{$cmd}) && -x $dir.$cmd);
   }
}
foreach my $cmd (@SYSCMD){
   if (!exists($SYSCMD{$cmd})){
      msg(ERROR,"missing posix command '%s' in PATH",$cmd);
      exit(1);
   }
}

if ($#ARGV<1){
   msg(ERROR,"missing SourceSpec + DestinationTabel Syntax");
   exit(1);
}

my @SOURCELIST=@ARGV;
my $DSTTAB=pop(@SOURCELIST);




#
# create temp file
#

my $TMP=tempdir(CLEANUP=>1);
my $SRCCSV;  # source temp file
my $CURCSV;  # current CSV 
my @FIELDS;  # fieldlist in CSV 1st Line
my $FIELDS;  # 1st Line of CSV
my %stat=(start=>time(),clr=>0,upd=>0,ins=>0,del=>0,ilines=>undef,clines=>undef);



foreach my $SOURCE (@SOURCELIST){
   #
   # load original file
   #

   if ($ARGV[0]=~m/^sftp:/){
      #  sftp://w5sftp/home/w5sapp01/incoming/P01DE_order_hier_DRW_*.csv
      my $url=$ARGV[0];
      my ($schema,$host,$dir,$filespec)=$url=~m#^(sftp)://([^/]+)(/.*)/([^/]+)$#;

      msg (INFO,"schema=$schema");
      msg (INFO,"host=$host");
      msg (INFO,"dir=$dir");
      msg (INFO,"filespec=$filespec");

      my $res=`echo 'version' | $SYSCMD{sftp} -b - \"$host\" 2>&1`;
      if ($?!=0){
         msg(ERROR,"$res");
         msg(ERROR,"connect check to $host failed");
         exit(1);
      }
      my $ftptemp=tempdir(CLEANUP=>1);

      
      my $res=`echo 'cd $dir\nls $filespec'| $SYSCMD{sftp}  -b - \"$host\" 2>&1`;
      if ($?!=0){
         msg(ERROR,"$res");
         msg(ERROR,"fail to load filelist from $host with filespec $filespec");
         exit(1);
      }
      foreach my $remotefile (split(/\n/,$res)){
          printf("Prozessing=%s\n",$remotefile);


      }



      

#      my $res=`echo 'lcd \"$ftptemp\"\ncd get *.csv' |
#                sftp -b - \"$sftpsource\" 2>&1`;
#      if ($?!=0){
#         $loaderror=$res;
#      }




#   if (!defined($loaderror)){
#      my $dh;
#      if (opendir($dh,$tempdir)){
#         @loadfiles=grep({ -f "$tempdir/$_" &&
#                           !($_=~m/^\./) } readdir($dh));
#         if ($#loadfiles==-1){
#            $loaderror="error - no files transfered from '$sftpsource'";
#         }
#      }
#      else{
#         $loaderror="fail to open dir '$tempdir': $?";
#      }
#   }





      exit(1);




   }
   else{
      if (-f $ARGV[0] && -r $ARGV[0]){
         msg(ERROR,"transfer source file to temp space");
         if (open(FI,"<$ARGV[0]")){
            $FIELDS=<FI>;         
            $stat{ifile}=$ARGV[0];
            $stat{ifile}=~s/^.*[\\\/]//;
            if (open(FO,">$TMP/base.csv")){
               $stat{ilines}=0;
               while(my $l=<FI>){
                  $stat{ilines}++;
                  if (length($l)>3200){
                     msg(ERROR,"csv records with more then 3200 char are not supported");
                     msg(ERROR,"input file $ARGV[0] line $stat{ilines}");
                     exit(1);
                  }
                  print FO $l;
               }
               close(FO);
            }
            else{
               MSG(ERROR,"fail to open temp csv");
               exit(1);
            }
            close(FI);
         }
         else{
            MSG(ERROR,"fail to open source csv '$ARGV[0]'");
            exit(1);
         }
         my $cmd="$SYSCMD{cat} '$TMP/base.csv'|".
                 "$SYSCMD{sort}|".
                 "$SYSCMD{uniq}".
                 ">'$TMP/source.csv'";
         printf STDERR ("fifi cmd=$cmd\n");
         system($cmd);
         unlink("$TMP/base.csv");
         if ($? == -1) {
             msg(ERROR,"failed to execute: $!\n");
             exit(1);
         }
         elsif ($? & 127) {
             msg(ERROR,"child died with signal %d, %s coredump\n",
                 ($? & 127),  ($? & 128) ? 'with' : 'without');
             exit(1);
         }
         elsif (( $? >> 8)!=0) {
             msg(ERROR,"child exited with value %d\n",$?>>8);
             exit(1);
         }
         $SRCCSV=$TMP."/source.csv";
      }
      else{
         msg(ERROR,"source file %s",$ARGV[0]);
         msg(ERROR,"can not open source file");
         exit(1);
      }
   }
   ProcessTempfile();
}



sub ProcessTempfile
{
   msg(INFO,"connect to Oracle database Schema");
   my ($dbi,$schema,$partner)=getOracleDBIConnectionHandle();

   $FIELDS=~s/\s*$//;
   my $c=1;
   @FIELDS=map({
      my $fld=sprintf("C%02d_",$c).$_;
      $fld=~s/[^a-z0-9]/_/gi;
      $fld=substr($fld,0,30);
      $c++;
      "$fld"
   } @{csvlinesplit($FIELDS)});





   #
   # Sicherstellen das Zieltabelle vorhanden
   #
   my $found=0;
   foreach my $tab (getOracleDBIschemaInfo($dbi,$schema)){
      if ($tab->{TABLE_TYPE} eq "TABLE" &&
          $tab->{'TABLE_NAME'} eq $DSTTAB){
         $found++;
      }
   }
   if (!$found){
      my $sql="create table \"$DSTTAB\" (".
              "\"W5_rawline\" varchar2(3200),".  # 3200 is oracle index limit!
              "\"W5_key\" varchar2(40),".
              "\"W5_mdate\" date not null,".
              "\"W5_cdate\" date not null,".
              "\"W5_isdel\" char(1) default '0',";
      $sql.=join(",",map({"\"$_\" varchar2(40)"} @FIELDS));
      $sql.=")";
      my $bk=$dbi->doCmd($sql);
      if ($bk ne "0E0"){
         msg(ERROR,"fail to create target table");
         exit(1);
      }
      my $sql="create index \"${DSTTAB}_i1\" on \"$DSTTAB\" (\"W5_key\")";
      my $bk=$dbi->doCmd($sql);
      if ($bk ne "0E0"){
         msg(ERROR,"fail to create i1 index for target table table");
         exit(1);
      }
      my $sql="create index \"${DSTTAB}_i2\" on \"$DSTTAB\" (\"W5_rawline\")";
      my $bk=$dbi->doCmd($sql);
      if ($bk ne "0E0"){
         msg(ERROR,"fail to create i2 index for target table table");
         exit(1);
      }
      my $sql="create index \"${DSTTAB}_i3\" on \"$DSTTAB\" (\"W5_mdate\")";
      my $bk=$dbi->doCmd($sql);
      if ($bk ne "0E0"){
         msg(ERROR,"fail to create i3 index for target table table");
         exit(1);
      }
   }



   my $ins_sth=$dbi->prepare(
      "insert into \"$DSTTAB\" ".
      "(\"W5_rawline\",\"W5_key\",\"W5_cdate\",\"W5_mdate\"".
      join("",map({",\"".$_."\""} @FIELDS)).
      ") ".
      " values(?,?,current_date,current_date".
      join("",map({",?"} @FIELDS)).
      ")"
   );

   my $upd_sth=$dbi->prepare(
      "update \"$DSTTAB\" set ".
      "\"W5_rawline\"=?,\"W5_mdate\"=current_date".
      join("",map({",\"".$_."\"=?"} @FIELDS)).
      " where \"W5_key\"=? and \"W5_isdel\"='0'"
   );

   my $clr_sth=$dbi->prepare(
      "delete from \"$DSTTAB\" where \"W5_isdel\"='1' ".
      "and \"W5_mdate\"<current_date-90  "
   );


   my $del_sth;

   if ($opt_a){
      $del_sth=$dbi->prepare(
         "update \"$DSTTAB\" set \"W5_isdel\"='1' ".
         "where \"W5_rawline\"=? and \"W5_isdel\"='0'"
      );
   }
   else{
      $del_sth=$dbi->prepare(
         "delete from \"$DSTTAB\" ".
         "where \"W5_rawline\"=? and \"W5_isdel\"='0'"
      );
   }




   #
   # bereits geladenen CSV Stand erzeugen
   #


   if (open(F,">$TMP/sqlcurrent.csv")){
      my $cmd="select \"W5_rawline\" from \"$DSTTAB\" where \"W5_isdel\"='0'";
      my $sth=$dbi->prepare($cmd);
      if ($sth->execute()){
         $stat{clines}=0;
         while(my $dbrec=$sth->fetchrow_hashref()){
             if (!($dbrec->{W5_rawline}=~m/\n$/)){
                msg(WARN,"line seperation error in target table - fixing it");
                $del_sth->execute($dbrec->{W5_rawline});
             }
             else{
                $stat{clines}++;
                print F ($dbrec->{W5_rawline});
             }
         }
      }
      close(F);
   }


   my $cmd="$SYSCMD{cat} '$TMP/sqlcurrent.csv'|".
           "$SYSCMD{sort}|".
           "$SYSCMD{uniq}".
           ">'$TMP/current.csv'";
   system($cmd);
   unlink("$TMP/sqlcurrent.csv");




   my $diffstream;
   my $cx;

   my $compcmd="$SYSCMD{comm} -3 \"$TMP/current.csv\" \"$TMP/source.csv\"";

   msg(INFO,"compare cmd = $compcmd");

   #exit(1);

   if (!open($diffstream,"$compcmd|")){
       msg(ERROR,"fail to open diff stream $!");
       exit(1);
   }

   sub csvlinesplit
   {
      my $line=shift;
      $line=~s/^\s*//;
      $line=~s/\s*$//;
      my $cols=[split(/;/,$line,-1)];
      return($cols);
   }


   sub getDiffOperation
   {
      my $s=shift;
      my $bufsz=5;

      if (!$main::streameof){
         do{
            my $line=<$s>;
            if (!$line){
               $main::streameof++;
            }
            else{
               my $rawline=$line;
               $rawline=~s/^\s*//;
               my $cols=csvlinesplit($line);
               my $newrec={
                  line=>$line,
                  rawline=>$rawline,
                  cols=>$cols
               };
               if ($opt_k>0){
                  $newrec->{key}=$cols->[$opt_k-1];
               }
               else{
                  $newrec->{key}=undef;
               }
               if ($newrec->{line}=~m/^\s/){
                  $newrec->{op}="insert";
               }
               else{
                  $newrec->{op}="delete";
               }
               push(@main::buffer,$newrec);
            }
         }while($#main::buffer<$bufsz && !$main::streameof);
      }
      return if ($#main::buffer==-1);
      my $op;
      $op=shift(@main::buffer);


      if ($opt_k>0){
         my $chkkey=$op->{key};
         my $foundAltOp;
         for(my $c=0;$c<=$#{main::buffer};$c++){
            if ($main::buffer[$c]->{key} eq $chkkey){
               $foundAltOp=$c;
               last;
            }
         }
         if (defined($foundAltOp)){
            if ($op->{op} eq "insert" &&
                $main::buffer[$foundAltOp]->{op} eq "delete"){
               splice(@main::buffer,$foundAltOp,1);
               #msg(INFO,"insert befor delete on key $chkkey");
               $op->{op}="update";
            }
            elsif ($op->{op} eq "delete" &&
                   $main::buffer[$foundAltOp]->{op} eq "insert"){
               ($op)=splice(@main::buffer,$foundAltOp,1);
               #msg(INFO,"delete befor insert on key $chkkey");
               $op->{op}="update";
            }
            else{
               msg(ERROR,"found invalid or not defined update constellation");
               exit(1);
            }
         }
      }





      
      return($op); 
   }





   my $c=0;
   my $sqlbk;
   while(my $op=getDiffOperation($diffstream)){
      $c++;
      if ($op->{op} eq "insert"){
         if ($#{$op->{cols}}!=$#FIELDS){
            printf STDERR ("colcount missmatch\n");
            printf STDERR ("l='%s'\n",$op->{rawline});
            printf STDERR ("c='%s'\n",join(";",@{$op->{cols}}));
            printf STDERR ("f='%s'\n",join(";",@FIELDS));
            $stat{colcnterr}++;
         }
            if (!($sqlbk=$ins_sth->execute($op->{rawline},$op->{key},
                                        @{$op->{cols}}))){
            msg(ERROR,"fail");
            exit(1);
         }
         $stat{ins}++;
      }
      elsif($op->{op} eq "delete"){
         if (!($sqlbk=$del_sth->execute(($op->{rawline})))){
            msg(ERROR,"fail");
            exit(1);
         }
         if ($sqlbk eq "0E0"){
            printf STDERR ("fifi sqlbk=$sqlbk line=$op->{rawline}\n");
         }
         $stat{del}++;
      }
      elsif($op->{op} eq "update"){
         if (!($sqlbk=$upd_sth->execute($op->{rawline},
                                        @{$op->{cols}},$op->{key}))){
            msg(ERROR,"update fail");
            exit(1);
         }
         if ($sqlbk eq "0E0"){
            msg(ERROR,"update fail on %s",Dumper($op));
            exit(1);
         }

         $stat{upd}++;
      }
      else{
         msg(ERROR,"operation '$op->{op}' not supported");
         exit(1);
      }
      if ($c % 49 == 0){
         $dbi->commit();
         $stat{commit}++;
      }
      if ($c % 1000 == 0){
         printf STDERR ("block:$c\n");
      }
     # printf("%d= size=%d op=%s\n",$c,length($op->{line}),$op->{op});
   }




   if (!close($diffstream)){
      msg(ERROR,"fail to process full diff stream $!");
      exit(1);
   }

   if (!($sqlbk=$clr_sth->execute())){
      msg(ERROR,"cleanup fail");
      exit(1);
   }
   if ($sqlbk ne "0E0"){
      $stat{clr}=$sqlbk;
   }

   $stat{end}=time();
   $stat{opcnt}=$stat{upd}+$stat{ins}+$stat{del};
   $stat{duration}=$stat{end}-$stat{start};

   print Dumper(\%stat);





      $dbi->commit();
      $dbi->disconnect();

   #printf STDERR ("replication duration=%d max=%d\n",time()-$ReplicationStart,
   #               $MaximumReplicationTime);

}
               
exit(0);

#==================================================================
sub Help
{
   printf("Usage: W5Replicate [OPTIONS] [OBJECTS]\n");
   printf("\n");
   my $form=" %-60s %17s\n";
   printf("OPTIONS:\n");
   printf($form,"--config     configuration file",
          "[replicate.conf]");
   printf($form,"--debug      enable debug messages",
          "[false]");
   printf($form,"--quietmode  disable all INFO messages to STDOUT",
          "[false]");
   printf($form,"--limittime  limit t for replication process in sec",
          "[60]");
   printf($form,"--phase      process the specified phases",
          "[1,2,3]");
   printf($form,"--tasks      limit the count of parallel processes",
          "[3]");
   printf("\n");
   printf("OBJECTS:\n");
   printf("None, one or more object names (in W5Base interal notation), ".
          "witch\nare should be replicated. If the Notation object(id) is ".
          "used,\nonly the specified record id will be replicated.\n".
          "f.e.:\n".
          "base::user base::grp itil::system !base::workflow ...\n".
          "base::location(12711643270034)\n\n");
}
#==================================================================


package DBI::st;

sub getHashList
{
   my $self=shift;
   my @bind=@_;
   my @l;

   if ($self->execute(@bind)){
      while(my $dbrec=$self->fetchrow_hashref()){
         push(@l,$dbrec);
      }
      return(@l);
   }
   return(undef);
}

sub getHash
{
   my $self=shift;
   my @bind=@_;
   my @l;

   if ($self->execute(@bind)){
      my $dbrec=$self->fetchrow_hashref();
      return($dbrec);
   }
   return(undef);
}

package DBI::db;
use kernel;

sub getHashList
{
   my $self=shift;
   my $cmd=shift;
   if (my $sth=$self->prepare($cmd)){
      return($sth->getHashList(@_));
   }
   return(undef);
}

sub getHash
{
   my $self=shift;
   my $cmd=shift;
   if (my $sth=$self->prepare($cmd)){
      my $dbrec=$sth->getHash(@_);
      $sth->finish();
      $self->commit();
      return($dbrec);
   }
   else{
      die("while prepare $cmd"); 
   }
   return(undef);
}

sub preprocessRecord
{
   my $self=shift;
   my ($obj,$ctrl,$reqrec,$col)=@_;
   my %rec=(%$reqrec);

   if (exists($rec{'replkeypri'}) && exists($rec{'replkeysec'})){
      # in Phase2 no replkeypri and replkeysec will be updated! This is
      # neassesary to ensure process in Phase1
      $rec{'w5replkey'}=sprintf("%35s%35s",$rec{'replkeypri'},
                                           $rec{'replkeysec'});
      $rec{'w5replkey'}=~s/ /0/g;
      $rec{'w5replkeypri'}=$rec{'replkeypri'};
      $rec{'w5replkeysec'}=$rec{'replkeysec'};
   }
   foreach my $k (@{$ctrl->{'replkeyfields'}}){
      delete($rec{$k});
   }
   foreach my $fieldname (keys(%rec)){
      my $fobj=$obj->getField($fieldname);
      my $forceHashHandling=0;
      if (defined($fobj)){
         if ($fobj->Type() eq "XMLInterface"){
            if (exists($rec{name}) && $rec{name} eq "W5Base/Darwin"){
               $forceHashHandling=1;
            }
         }
      }
      if (scalar($rec{$fieldname}) =~ m/^Container=HASH/) {
         $rec{$fieldname}=$self->Hash2DataField($forceHashHandling,
                                                $rec{$fieldname});
      }
      if (ref($rec{$fieldname}) eq "ARRAY"){
         if ($#{$rec{$fieldname}}>=0){
            if (ref($rec{$fieldname}->[0]) ne "HASH"){
               $rec{$fieldname}=join("; ",@{$rec{$fieldname}});
            }
            else{
               $rec{$fieldname}=$self->Hash2DataField($forceHashHandling,
                                                      $rec{$fieldname});
            }
         }
         else{
            $rec{$fieldname}=undef;
         }
      }
      if (ref($rec{$fieldname}) eq "HASH"){
         $rec{$fieldname}=$self->Hash2DataField($forceHashHandling,
                                                $rec{$fieldname});
      }
      # strip all field values to the max. length in the replication
      # schema. This prevent oracle SQL Errors
      if (exists($col->{$fieldname})){
         if ($col->{$fieldname}->{'type'} =~ m/^[char|varchar]/i) {
            if (length($rec{$fieldname})>$col->{$fieldname}->{'size'}){
               $rec{$fieldname}=substr($rec{$fieldname},0,
                                       $col->{$fieldname}->{'size'});
            }
         }
      }
   }
   return(\%rec);
}


sub isChanged
{
   my $self=shift;
   my $ctrl=shift;
   my $oldrec=shift;
   my $newrec=shift;

   my $changecount=0;
   foreach my $k (keys(%$newrec)){
      if (!($k=~m/^w5repl.*$/i)){

        my $new=$newrec->{$k};
         my $old=$oldrec->{$k};
         if (trim($new) ne trim($old)){
            $changecount++;
            msg(INFO,sprintf("%s: old='%s' new='%s'",$k,$oldrec->{$k},
                                                        $newrec->{$k}));
         }
      }
   }
   return($changecount);
}




sub InsertOrUpdate
{
   my $self=shift;
   my $obj=shift;
   my $ctrl=shift;
   my $reqrec=shift;
   my $dbtable=$ctrl->{'name'};
   my $idname=$ctrl->{'idname'};
   my $col=$ctrl->{'col'};
   my ($bk,@w5v,@w5p,@w5b);

   my $rec=$self->preprocessRecord($obj,$ctrl,$reqrec,$col);

   my $cmd="select * from \"$dbtable\" where $idname=?";
   my $idval=$rec->{$idname};
   msg(INFO,"query ($idval): $cmd");
   my @curlist=$self->getHashList($cmd,$idval);

   # hier muß die view noch sortiert werden, da wenn die LOB Felder nicht
   # am Ende des Statements stehen, ein ORA-24816 auftaucht.
   my @view=sort({
      my $pa="100";
      my $pb="100";
      my @lobs=qw(CLOB LOB BLOB);
      $pa=900 if (in_array(\@lobs,$col->{$a}->{type}));
      $pb=900 if (in_array(\@lobs,$col->{$b}->{type}));
      $pa.$a cmp $pb.$b;
   } keys(%$rec));

   if ($#curlist==0){     # do an update
      my $isChanged=$self->isChanged($ctrl,$curlist[0],$rec);
      my (@v,@values);
      foreach my $fieldname (@view){
         if ($fieldname=~m/^w5repl.*/i){
            push(@w5v,$fieldname);
            push(@w5p,"?");
            push(@w5b,$rec->{$fieldname});
            delete($rec->{$fieldname});
         }
         else{
            push(@values,$rec->{$fieldname});
            if ($col->{$fieldname}->{type} =~ m/^(timestamp|date)/i) {
               push(@v,"$fieldname=to_date(?,'YYYY-MM-DD HH24:MI:SS')");
            }
            else {
               push(@v,"$fieldname=?");
            }
         }
      }
      if ($isChanged){
         push(@w5v,"w5replmdate");
         push(@w5p,"current_date");
      }
      my $v=join(",",@v);
      my $updcmd="update \"$dbtable\" set $v where $idname=?";
      msg(INFO,"upd ($idval): $updcmd (".
               join(",",map({"'".$_."'"} @values,$idval)).")");
      $bk=$self->doCmd($updcmd,@values,$idval);
   }
   elsif ($#curlist==-1){ # do an insert
      my @values;
      my @place;
      my @insview;
      foreach my $fieldname (@view) {
         if ($fieldname=~m/^w5repl.*/i){
            push(@w5v,$fieldname);
            push(@w5p,"?");
            push(@w5b,$rec->{$fieldname});
            delete($rec->{$fieldname});
         }
         else{
            push(@insview,$fieldname);
            push(@values,$rec->{$fieldname});
            if ($col->{$fieldname}->{type} =~ m/^[timestamp|date]/i) {
               push(@place,"to_date(?,'YYYY-MM-DD HH24:MI:SS')");
            }
            else {
               push(@place,"?");
            }
         }
      }
      #my @values=map({$rec->{$_}} @view);
      #my @place=map({'?'} @view);
     # if (exists($ctrl->{'col'}->{'w5replmdate'})){
     #    push(@w5v,'w5replmdate');
     #    push(@w5p,'current_date');
     # }
     # if (exists($ctrl->{'col'}->{'w5replcdate'})){
     #    push(@w5v,'w5replcdate');
     #    push(@w5p,'current_date');
     # }
      
      my $inscmd="insert into \"$dbtable\" ".
        "(".join(",",@insview).") values(".join(",",@place).")";
      msg(INFO,"ins ($idval): $inscmd");
      $bk=$self->doCmd($inscmd,@values);
   }
   else{
      msg(ERROR,"ganz scheisse!");
      exit(-12356);
   }
   if ($bk){  # now store the current state of object in state table _
      push(@w5v,'w5repllastsucc');
      push(@w5p,'current_date');
      push(@w5v,'w5repllasttry');
      push(@w5p,'current_date');
      push(@w5v,"w5replfailcnt");
      push(@w5p,"0");
      my $cmd="select refid from \"_$dbtable\" where refid=?";
      my @curlist=$self->getHashList($cmd,$idval);
      if ($#curlist==0){     # do an update
         my @v;
         for(my $c=0;$c<=$#w5v;$c++){
            push(@v,$w5v[$c]."=".$w5p[$c]);
         }
         my $updcmd="update \"_$dbtable\" set ".
                    join(",",@v)." where refid=?";
         $bk=$self->doCmd($updcmd,@w5b,$idval);
      }
      else{
         if (!in_array(\@w5v,"w5replmdate")){
            push(@w5v,'w5replmdate');
            push(@w5p,'current_date');
         }
         push(@w5v,'w5replcdate');
         push(@w5p,'current_date');
         push(@w5v,'refid');
         push(@w5p,'?');
         push(@w5b,$idval);
         my $inscmd="insert into \"_$dbtable\" ".
           "(".join(",",@w5v).") ".
           "values(".join(",",@w5p).")";
         msg(INFO,"w5ins: $inscmd :",join(",",@w5b));
         $bk=$self->doCmd($inscmd,@w5b);
      }
   }
   return($bk);
}



sub Hash2DataField
{
   my $self=shift;
   my $forceHashHandling=shift;
   my $container=shift;
   my $element;

   if ($forceHashHandling){
     return(utf8(hash2xml($container))->latin1());
   }
   elsif (ref($container) eq "ARRAY"){
     return(utf8(hash2xml({'struct'=>{'entry'=>$container}}))->latin1());
   }
   elsif (exists($container->{'item'}) && 
       scalar($container->{'item'}) =~ m/^ARRAY/) {
      foreach my $item (@{$container->{'item'}}) {
         $element.=$item->{'name'}.
                   "='".$item->{'value'}."'=".
                   $item->{'name'}."\n";
      }
   }
   else{
     return("<struct><entry>".
            utf8(hash2xml($container))->latin1()."</entry></struct>");
   }
   return($element);
}

sub effectedRows
{
   my $self=shift;
   return($self->{effectedRows});
}

sub doCmd
{
   my $self=shift;
   my $cmd=shift;

   if (
       ($cmd=~m/^\s*create\s+table\s/i) ||
       ($cmd=~m/^\s*create\s+index\s/i) ||
       ($cmd=~m/^\s*alter\s+table\s/i)
      ){
      msg(INFO,"reset schemaInfoCache in process $$ for cmd='$cmd'");
      $W5REPL::schemaInfoCache=undef;  # clear schema cache
   }



   $self->{effectedRows}=undef;
   if (my $sth=$self->prepare($cmd)){
      my $bk=$sth->execute(@_);
      $self->{effectedRows}=$sth->rows();
      return($bk);
   }
   return(undef);
}




