#!/usr/bin/env perl
use FindBin;
use lib "$FindBin::Bin/../lib";
use RPC::Smart::Client;
use Data::Dumper;
use strict;
use kernel;
use kernel::config;
use Getopt::Long;
use vars qw($opt_v $opt_h $opt_c $configname);

#######################################################################
#   STD procedure for every Shell entry point to W5Base environment
#            Init of global W5V2::INSTDIR and W5V2::INSTPATH
#
if ($ENV{W5BASEINSTDIR} eq "" && -f "/etc/environment"){
   exec('bash','-lc','/etc/environment',$0,$^X,$0,@ARGV);
}
if (!defined($W5V2::INSTDIR)){
   if (defined(&{FindBin::again})){
      eval('FindBin::again();');
      if (!defined($@)){
         $W5V2::INSTDIR="$FindBin::Bin/..";
      }
   }
}
$W5V2::INSTDIR="/opt/w5base" if (!defined($W5V2::INSTDIR));
$W5V2::INSTPATH=[];
my @w5instpath;
if ($ENV{W5BASEINSTDIR} ne ""){
   @w5instpath=split(/:/,$ENV{W5BASEINSTDIR});
   $W5V2::INSTDIR=shift(@w5instpath);
   $W5V2::INSTPATH=\@w5instpath;
}
foreach my $path (map({$_."/mod",$_."/lib"} $W5V2::INSTDIR),
                  map({$_."/mod"} @w5instpath)){
   my $qpath=quotemeta($path);
   unshift(@INC,$path) if (!grep(/^$qpath$/,@INC));
}
#######################################################################


exit(1) if (!GetOptions('verbose'=>\$opt_v,
                        'debug'=>\$opt_v,
                        'help'=>\$opt_h,
                        'config=s'=>\$opt_c));

if ($opt_v){
   $W5V2::Debug=1;
}
else{
   $W5V2::Debug=0;
}

if ($opt_c eq ""){
   $opt_c="w5server";
}
$configname=$opt_c;

my %ClientParam=();

my $configcheck=new kernel::config();

if (!$configcheck->readconfig("$FindBin::Bin/..",$configname)){
   msg(ERROR,"can't read configfile '%s'",$configname);
   exit(1);
}
{
   my $port=$configcheck->Param("W5SERVERPORT");
   $port=4711 if ($port eq "");
   msg(DEBUG,"W5ServerPort=%s",$port);
   $ClientParam{'PeerPort'}=$port;
}

my $MyClient=new RPC::Smart::Client(%ClientParam);

if (! defined($MyClient->Connect())){
   msg(ERROR,"can't connect to server");
   exit(1);
}
my $method="rpcCallSpooledEvent";
my %p=(eventname=>'sample1',
       spooltag=>'tst123',
       redefine=>'1',
       firstcalldelay=>5,
       userid=>11634953080001);

my $res=$MyClient->Call($method,%p);
printf("%s",Dumper($res)) if ($W5V2::Debug);
if ($res->{exitcode}==0 && defined($res->{AsyncID})){
   my $sec=0;
   while(1){
      if ($W5V2::Debug){
         printf("   ----------- sec=%5d -------------\n",$sec);
      }
      my $st=$MyClient->Call("rpcProcessState",$res->{AsyncID});
      printf("%s",Dumper($st)) if ($W5V2::Debug);
      last if (defined($st->{process}) && defined($st->{process}->{exitcode}));
      last if (defined($st->{exitcode}) && $st->{exitcode}!=0);
      $sec++;
      sleep(1);
   }
}
