#!/bin/sh
#
# This file was produced by running the Configure script. It holds all the
# definitions figured out by Configure. Should you modify one of these values,
# do not forget to propagate your changes by running "Configure -der". You may
# instead choose to run each of the .SH files by yourself, or "Configure -S".
#

# Package name      : IPC-ShareLite
# Source directory  : .
# Configuration time: Tue May 10 12:06:32 CEST 2011
# Configured by     : hvogler
# Target system     : linux ak1ld168 2.6.18-194.17.4.el5 #1 smp wed oct 20 13:03:08 edt 2010 x86_64 x86_64 x86_64 gnulinux 

Author=''
Date=''
Header=''
Id=''
Locker=''
Log=''
Mcc=''
RCSfile=''
Revision=''
Source=''
State=''
ar=''
archobjs=''
awk='/bin/awk'
bash=''
bison=''
byacc=''
c=''
cat='/bin/cat'
cf_by='hvogler'
cf_time='Tue May 10 12:06:32 CEST 2011'
chgrp=''
chmod=''
chown=''
comm=''
compress=''
contains='grep'
cp=''
cpio=''
cpp='/usr/bin/cpp'
cpplast='-'
cppminus='-'
cpprun='cc -E'
cppstdin='cc -E'
csh=''
d_bsd='undef'
d_eunice='undef'
d_gnulibc='undef'
d_portable='undef'
d_sem='define'
d_semctl='define'
d_semctl_semid_ds='define'
d_semctl_semun='define'
d_semget='define'
d_semop='define'
d_union_semun='undef'
d_xenix='undef'
date='/bin/date'
defvoidused='15'
echo='/bin/echo'
egrep=''
emacs=''
eunicefix=':'
expr='/usr/bin/expr'
find=''
firstmakefile=''
flex=''
gcc=''
glibpth='/shlib /usr/shlib /lib/pa1.1 /usr/lib/large /lib /usr/lib /usr/lib/386 /lib/386 /lib/large /usr/lib/small /lib/small /usr/ccs/lib /usr/ucblib /usr/local/lib'
grep='/bin/grep'
gzip=''
hint='previous'
incpath=''
inews=''
ksh=''
less=''
libc=''
libpth=' /usr/local/lib /lib /usr/lib'
libs=' '
line=''
lint=''
ln='/bin/ln'
lns='/bin/ln -s'
loclibpth='/usr/local/lib /opt/local/lib /usr/gnu/lib /opt/gnu/lib /usr/GNU/lib /opt/GNU/lib'
lp=''
lpr=''
ls=''
mail=''
mailx=''
make=''
mips=''
mips_type=''
mkdir=''
more=''
mv=''
myuname='linux ak1ld168 2.6.18-194.17.4.el5 #1 smp wed oct 20 13:03:08 edt 2010 x86_64 x86_64 x86_64 gnulinux '
n=''
nm_opt=''
nm_so_opt='--dynamic'
nroff=''
osname=''
osvers=''
package='IPC-ShareLite'
perl=''
pg=''
plibpth=''
pmake=''
pr=''
rm='/bin/rm'
rmail=''
runnm='false'
sed='/bin/sed'
sendmail=''
sh='/bin/sh'
shar=''
sharpbang='#!'
shsharp='true'
sleep=''
smail=''
so='so'
sort=''
spackage=''
spitshell='cat'
src='.'
startsh='#!/bin/sh'
submit=''
tail=''
tar=''
tbl=''
test='test'
touch='/bin/touch'
tr='/usr/bin/tr'
troff=''
uname='/bin/uname'
uniq=''
usenm='false'
usrinc='/usr/include'
uuname=''
vi=''
voidflags='15'
xlibpth='/usr/lib/386 /lib/386'
zcat=''
zip=''
CONFIG=true
