create table artcatalog (
  id         bigint(20)  NOT NULL,
  name       varchar(40) NOT NULL, 
  frontlabel longtext, 
  mandator   bigint(20)  NOT NULL,
  databoss   bigint(20)  NOT NULL,
  cistatus   int(2)      NOT NULL,
  description longtext,
  comments    longtext,
  additional  longtext,
  logo_small  blob,
  logo_large  blob,
  createdate datetime NOT NULL default '0000-00-00 00:00:00',
  modifydate datetime NOT NULL default '0000-00-00 00:00:00',
  createuser bigint(20) NOT NULL default '0',
  modifyuser bigint(20) NOT NULL default '0',
  editor     varchar(100) NOT NULL default '',
  realeditor varchar(100) NOT NULL default '',
  srcsys     varchar(100) default 'w5base',
  srcid      varchar(20) default NULL,
  srcload    datetime    default NULL,
  PRIMARY KEY  (id),
  key name(name),
  UNIQUE KEY `srcsys` (srcsys,srcid)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
create table artcategory (
  id           bigint(20)  NOT NULL,
  artcatalog   bigint(20)  NOT NULL, 
  partcategory bigint(20), 
  posno          int(7)      NOT NULL,
  frontlabel     longtext, 
  sublabel       longtext, 
  description longtext,
  comments    longtext,
  additional  longtext,
  logo_small  blob,
  logo_large  blob,
  createdate datetime NOT NULL default '0000-00-00 00:00:00',
  modifydate datetime NOT NULL default '0000-00-00 00:00:00',
  createuser bigint(20) NOT NULL default '0',
  modifyuser bigint(20) NOT NULL default '0',
  editor     varchar(100) NOT NULL default '',
  realeditor varchar(100) NOT NULL default '',
  srcsys     varchar(100) default 'w5base',
  srcid      varchar(20) default NULL,
  srcload    datetime    default NULL,
  PRIMARY KEY  (id),
  FOREIGN KEY parentcategory (partcategory)
          REFERENCES artcategory (id) ON DELETE CASCADE,
  FOREIGN KEY articlecatalog (artcatalog)
          REFERENCES artcatalog (id) ON DELETE RESTRICT,
  UNIQUE KEY `positionnumber` (artcatalog,posno),
  UNIQUE KEY `srcsys` (srcsys,srcid)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
create table artproduct (
  id           bigint(20)  NOT NULL,
  artcategory  bigint(20), 
  posno        int(7),
  variantof    bigint(20),
  variant      varchar(40) default 'standard',
  frontlabel   longtext, 
  pstatus      int(2)      NOT NULL,
  productmgr   bigint(20)  NOT NULL, 
  orderable_from datetime default NULL,
  orderable_to   datetime default NULL,
  cost_once      double(36,2) default NULL,
  cost_day       double(36,2) default NULL,
  cost_month     double(36,2) default NULL,
  cost_year      double(36,2) default NULL,
  cost_peruse    double(36,2) default NULL,
  produnit       varchar(30)  default NULL,
  currency       varchar(10)  default 'EUR',
  billinterval   varchar(30)  default NULL,
  description longtext,
  comments    longtext,
  additional  longtext,
  logo_small  blob,
  logo_large  blob,
  createdate datetime NOT NULL default '0000-00-00 00:00:00',
  modifydate datetime NOT NULL default '0000-00-00 00:00:00',
  createuser bigint(20) NOT NULL default '0',
  modifyuser bigint(20) NOT NULL default '0',
  editor     varchar(100) NOT NULL default '',
  realeditor varchar(100) NOT NULL default '',
  srcsys     varchar(100) default 'w5base',
  srcid      varchar(20) default NULL,
  srcload    datetime    default NULL,
  PRIMARY KEY  (id),
  FOREIGN KEY articlecategory (artcategory)
          REFERENCES artcategory (id) ON DELETE CASCADE,
  UNIQUE KEY `positionnumber` (artcategory,posno),
  UNIQUE KEY `srcsys` (srcsys,srcid)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
create table artdelivprovider (
  id         bigint(20)  NOT NULL,
  name       varchar(40) NOT NULL, 
  frontlabel longtext, 
  mandator   bigint(20)  NOT NULL,
  databoss   bigint(20)  NOT NULL,
  cistatus   int(2)      NOT NULL,
  description longtext,
  comments    longtext,
  createdate datetime NOT NULL default '0000-00-00 00:00:00',
  modifydate datetime NOT NULL default '0000-00-00 00:00:00',
  createuser bigint(20) NOT NULL default '0',
  modifyuser bigint(20) NOT NULL default '0',
  editor     varchar(100) NOT NULL default '',
  realeditor varchar(100) NOT NULL default '',
  srcsys     varchar(100) default 'w5base',
  srcid      varchar(20) default NULL,
  srcload    datetime    default NULL,
  PRIMARY KEY  (id),
  key name(name),
  UNIQUE KEY `srcsys` (srcsys,srcid)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
create table artdelivelement (
  id         bigint(20)  NOT NULL,
  artdelivprovider  bigint(20)  NOT NULL,
  frontlabel        longtext, 
  description longtext,
  comments    longtext,
  createdate datetime NOT NULL default '0000-00-00 00:00:00',
  modifydate datetime NOT NULL default '0000-00-00 00:00:00',
  createuser bigint(20) NOT NULL default '0',
  modifyuser bigint(20) NOT NULL default '0',
  editor     varchar(100) NOT NULL default '',
  realeditor varchar(100) NOT NULL default '',
  srcsys     varchar(100) default 'w5base',
  srcid      varchar(20) default NULL,
  srcload    datetime    default NULL,
  PRIMARY KEY  (id),
  FOREIGN KEY deliverypartner (artdelivprovider)
          REFERENCES artdelivprovider (id) ON DELETE RESTRICT,
  UNIQUE KEY `srcsys` (srcsys,srcid)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
create table lnkartelementprod (
  id         bigint(20)  NOT NULL,
  artdelivelement  bigint(20)  NOT NULL,
  artproduct       bigint(20)  NOT NULL,
  comments    longtext,
  createdate datetime NOT NULL default '0000-00-00 00:00:00',
  modifydate datetime NOT NULL default '0000-00-00 00:00:00',
  createuser bigint(20) NOT NULL default '0',
  modifyuser bigint(20) NOT NULL default '0',
  editor     varchar(100) NOT NULL default '',
  realeditor varchar(100) NOT NULL default '',
  srcsys     varchar(100) default 'w5base',
  srcid      varchar(20) default NULL,
  srcload    datetime    default NULL,
  PRIMARY KEY  (id),           
  FOREIGN KEY deliveryelement (artdelivelement)
          REFERENCES artdelivelement (id) ON DELETE CASCADE,
  FOREIGN KEY product (artproduct)
          REFERENCES artproduct (id) ON DELETE CASCADE,
  UNIQUE KEY `srcsys` (srcsys,srcid)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
