use w5base;
create table softwareset (
  id          bigint(20)  NOT NULL,
  name        varchar(80) NOT NULL,
  cistatus    int(2)      NOT NULL,
    mandator       bigint(20)  default NULL,
    databoss       bigint(20)  default NULL,
  comments    longtext     default NULL,
  additional  longtext     default NULL,
  createdate  datetime NOT NULL default '0000-00-00 00:00:00',
  modifydate  datetime NOT NULL default '0000-00-00 00:00:00',
  createuser  bigint(20) NOT NULL default '0',
  modifyuser  bigint(20) NOT NULL default '0',
  editor      varchar(100) NOT NULL default '',
  realeditor  varchar(100) NOT NULL default '',
  srcsys      varchar(100) default 'w5base',
  srcid       varchar(20) default NULL,
  srcload     datetime    default NULL,
  PRIMARY KEY  (id),
  UNIQUE KEY name (name),
  UNIQUE KEY `srcsys` (srcsys,srcid)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
create table lnksoftwaresoftwareset (
  id           bigint(20) NOT NULL,
  softwareset  bigint(20) NOT NULL,
  software     bigint(20) NOT NULL,
  version      varchar(30),
  releasekey   char(30) default '000000000000000000000000000000',
  comparator   int(1)   default '0', startwith varchar(20),
  comments     longtext    default NULL,
  additional   longtext    default NULL,
  createdate   datetime NOT NULL default '0000-00-00 00:00:00',
  modifydate   datetime NOT NULL default '0000-00-00 00:00:00',
  createuser   bigint(20) default NULL,
  modifyuser   bigint(20) default NULL,
  editor       varchar(100) NOT NULL default '',
  realeditor   varchar(100) NOT NULL default '',
  srcsys       varchar(100) default 'w5base',
  srcid        varchar(20) default NULL,
  srcload      datetime    default NULL,
  PRIMARY KEY  (id), KEY software (software),key(releasekey),key(softwareset),
  UNIQUE KEY `srcsys` (srcsys,srcid)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
create table lnkosreleasesoftwareset (
  id           bigint(20) NOT NULL,
  softwareset  bigint(20) NOT NULL,
  osrelease    bigint(20) NOT NULL,
  comparator   char(1)  default '0', 
  comments     longtext    default NULL,
  additional   longtext    default NULL,
  createdate   datetime NOT NULL default '0000-00-00 00:00:00',
  modifydate   datetime NOT NULL default '0000-00-00 00:00:00',
  createuser   bigint(20) default NULL,
  modifyuser   bigint(20) default NULL,
  editor       varchar(100) NOT NULL default '',
  realeditor   varchar(100) NOT NULL default '',
  srcsys       varchar(100) default 'w5base',
  srcid        varchar(20) default NULL,
  srcload      datetime    default NULL,
  PRIMARY KEY  (id), KEY software (osrelease),key(softwareset),
  UNIQUE KEY `srcsys` (srcsys,srcid)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
set FOREIGN_KEY_CHECKS=0;
create table applcitransfer (
  id           bigint(20) NOT NULL,
  eappl        bigint(20) NOT NULL,
  cappl        bigint(20) NOT NULL,
   eappl_ack_date   datetime     default NULL,
   eappl_ack_user   bigint(20)   default NULL,
   eappl_ack_cmnt   longtext     default NULL,
   cappl_ack_date   datetime     default NULL,
   cappl_ack_user   bigint(20)   default NULL,
   cappl_ack_cmnt   longtext     default NULL,
  configitems  longtext    default NULL,
  transferdt   datetime    default NULL,
  transferlog  longtext    default NULL,
  comments     longtext    default NULL,
  additional   longtext    default NULL,
  createdate   datetime NOT NULL default '0000-00-00 00:00:00',
  modifydate   datetime NOT NULL default '0000-00-00 00:00:00',
  createuser   bigint(20) default NULL,
  modifyuser   bigint(20) default NULL,
  editor       varchar(100) NOT NULL default '',
  realeditor   varchar(100) NOT NULL default '',
  srcsys       varchar(100) default 'w5base',
  srcid        varchar(20) default NULL,
  srcload      datetime    default NULL,
  PRIMARY KEY  (id),
  FOREIGN KEY fk_eappl (eappl) REFERENCES appl (id) ON DELETE CASCADE,
  FOREIGN KEY fk_cappl (cappl) REFERENCES appl (id) ON DELETE CASCADE,
  UNIQUE KEY `srcsys` (srcsys,srcid)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
