use w5base;
create table supcontract (
  id         bigint(20) NOT NULL,
  name       varchar(40) NOT NULL,
  cistatus   int(2)      NOT NULL,
    fullname       varchar(80) default NULL,
    contractid     varchar(20) default NULL,
    custorderno    varchar(20) default NULL,
    contractclass  varchar(20) default NULL,
    contractcoord  bigint(20)  default NULL,
    databoss       bigint(20)  default NULL,
    sem            bigint(20)  default NULL,
    sem2           bigint(20)  default NULL,
    conumber varchar(40) default NULL,
    mandator       bigint(20)  default NULL,
    responseteam   bigint(20)  default NULL,
    durationstart  datetime NOT NULL default '0000-00-00 00:00:00',
    durationend    datetime    default NULL,
    autoexpansion  int(20)     default NULL,
    cancelperiod   int(20)     default NULL,
    producer       bigint(20)  default NULL,
    description    longtext    default NULL,
    additional     longtext    default NULL,
  comments    longtext     default NULL,
  createdate datetime NOT NULL default '0000-00-00 00:00:00',
  modifydate datetime NOT NULL default '0000-00-00 00:00:00',
  createuser bigint(20) default NULL,
  modifyuser bigint(20) default NULL,
  lastqcheck datetime default NULL,
  editor     varchar(100) NOT NULL default '',
  realeditor varchar(100) NOT NULL default '',
  srcsys     varchar(100) default 'w5base',
  srcid      varchar(20) default NULL,
  srcload    datetime    default NULL,
  PRIMARY KEY  (id),key(lastqcheck),
  UNIQUE KEY contractid (contractid),
  UNIQUE KEY name (name,producer),
  UNIQUE KEY `srcsys` (srcsys,srcid)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
create table lnkapplsupcontract (
  id           bigint(20) NOT NULL,
  appl         bigint(20) NOT NULL,
  supcontract bigint(20) NOT NULL,
  fraction     double(8,2) default '100.00',
  createdate   datetime NOT NULL default '0000-00-00 00:00:00',
  modifydate   datetime NOT NULL default '0000-00-00 00:00:00',
  createuser   bigint(20) default NULL,
  modifyuser   bigint(20) default NULL,
  editor       varchar(100) NOT NULL default '',
  realeditor   varchar(100) NOT NULL default '',
  srcsys       varchar(100) default 'w5base',
  srcid        varchar(20) default NULL,
  srcload      datetime    default NULL,
  PRIMARY KEY  (id),
  KEY appl (appl),
  KEY supcontract (supcontract),
  UNIQUE KEY `srcsys` (srcsys,srcid)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
