use w5base;
create table comajobtiming (
  id          bigint(20)   NOT NULL,
  jobtype     varchar(20)  NOT NULL,
  jobid       bigint(20)   NOT NULL,
  systemid    bigint(20)   NOT NULL, 
  tinterval   int(2)       NOT NULL, 
  cistatus    int(2)       NOT NULL,
  plannedyear    int(20), 
  plannedmon     int(20), 
  plannedday     int(20), 
  plannedhour    int(20), 
  plannedmin     int(20), 
  plannedwdmon     int(1), 
  plannedwdtue     int(1), 
  plannedwdwed     int(1), 
  plannedwdthu     int(1), 
  plannedwdfri     int(1), 
  plannedwdsat     int(1), 
  plannedwdsun     int(1), 
  runcount       int(5), 
  synccontrol    int(2), 
  maxlatency     int(2), 
  lastjobstart     datetime,
  lastjobfineok    datetime,
  lastjobid        bigint(20), 
  lastexitcode     bigint(20), 
  editor      varchar(100) NOT NULL default '',
  realeditor  varchar(100) NOT NULL default '',
  modifydate  datetime   NOT NULL default '0000-00-00 00:00:00',
  modifyuser  bigint(20) NOT NULL default '0',
  createdate  datetime   NOT NULL default '0000-00-00 00:00:00',
  createuser  bigint(20) NOT NULL default '0',
  srcsys     varchar(10) default 'w5base',
  srcid      varchar(20) default NULL,
  srcload    datetime    default NULL,
  PRIMARY KEY  (id),
  key systemid (systemid,jobid,jobtype) ,key(tinterval),key(cistatus),
  key(lastjobstart,lastexitcode),unique src (srcid,srcsys)
);
