#! /bin/sh

c="1 2 3 4 5 6 7 8 9 0"


# even "no djblibs" needs buffer for strhash_save and _load. 
./auto-compilew.sh -UDJBLIBS -o stdc_check check_base.c $f \
  libuomisc.a libstrhash.a libunix.a libbyte.a \
  -pg || exit 1
./auto-compilew.sh -DDJBLIBS -o djb_check check_base.c $f \
  libuomisc.a libstrhash.a libunix.a libbyte.a \
  -pg  || exit 1

for i in $c ; do
time ./stdc_check >stdc_check.out || exit 1
mv gmon.out gmon.stdc.out.$i 
done

for i in $c ; do
time ./djb_check >djb_check.out || exit 1
mv gmon.out gmon.djb.out.$i 
done

gprof djb_check gmon.djb.out.* >djb.mon
gprof stdc_check gmon.stdc.out.* >stdc.mon
rm -f stdc_check stdc_check.out
rm -f djb_check djb_check.out
