/*
 * reimplementation of Daniel Bernsteins unix library.
 * placed in the public domain by Uwe Ohse, uwe@ohse.de.
 * This file is automatically generated.
 */

#ifndef ERROR_H
#define ERROR_H
#include <errno.h>
#ifndef errno
extern int errno; /* for really old systems */
#endif
extern const char *error_str(int);
extern int error_temp(int);

extern const int error_acces;
extern const int error_again;
extern const int error_connrefused;
extern const int error_exist;
extern const int error_inprogress;
extern const int error_intr;
extern const int error_io;
extern const int error_isdir;
extern const int error_mlink;
extern const int error_nodevice;
extern const int error_noent;
extern const int error_nomem;
extern const int error_perm;
extern const int error_pipe;
extern const int error_proto;
extern const int error_timeout;
extern const int error_txtbsy;
extern const int error_wouldblock;
extern const int error_afnosupport;
extern const int error_connreset;

#endif
