"${instdir}/lib/javascript/toolbox.kernel.js"
"${instdir}/lib/javascript/jquery.js"
"${instdir}/lib/javascript/utf8.js"
"${instdir}/lib/javascript/sprintf.js"
"${instdir}/lib/javascript/J5Base.kernel.js"
