use w5base;
create table articlegroup (
  id          bigint(20)  NOT NULL,
  name        varchar(128) NOT NULL,
  cistatus    int(2)      NOT NULL,
    mandator     bigint(20)  default NULL,
    databoss     bigint(20)  default NULL,
    duty         float(5,2)  default NULL,
    surcharge    float(5,2)  default NULL,
  description longtext     default NULL,
  comments    longtext     default NULL,
  additional  longtext     default NULL,
  createdate  datetime NOT NULL default '0000-00-00 00:00:00',
  modifydate  datetime NOT NULL default '0000-00-00 00:00:00',
  lastqcheck  datetime default NULL,
  createuser  bigint(20) NOT NULL default '0',
  modifyuser  bigint(20) NOT NULL default '0',
  editor      varchar(100) NOT NULL default '',
  realeditor  varchar(100) NOT NULL default '',
  srcsys      varchar(100) default 'w5base',
  srcid       varchar(20) default NULL,
  srcload     datetime    default NULL,
  PRIMARY KEY  (id),
  UNIQUE KEY srcsys (srcsys,srcid),
  UNIQUE KEY name (name),
  KEY qcheck (lastqcheck)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
create table articletag (
  id          bigint(20)  NOT NULL,
  name        varchar(128) NOT NULL,
  article     bigint(20)  NOT NULL,
  createdate  datetime NOT NULL default '0000-00-00 00:00:00',
  modifydate  datetime NOT NULL default '0000-00-00 00:00:00',
  lastqcheck  datetime default NULL,
  createuser  bigint(20) NOT NULL default '0',
  modifyuser  bigint(20) NOT NULL default '0',
  editor      varchar(100) NOT NULL default '',
  realeditor  varchar(100) NOT NULL default '',
  srcsys      varchar(100) default 'w5base',
  srcid       varchar(20) default NULL,
  srcload     datetime    default NULL,
  PRIMARY KEY  (id),
  UNIQUE KEY srcsys (srcsys,srcid),
  KEY name (name)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
create table article (
  id          bigint(20)  NOT NULL,
  name        varchar(128) NOT NULL,
  shortname   varchar(128) NOT NULL,
  cistatus    int(2)      NOT NULL,
    unitname      char(20)    default NULL,
    articlegroup  bigint(20)  default NULL,
    scurrency     char(20)    default NULL,
    purcaseprice  float(17,2) default NULL,
    internalprice float(17,2) default NULL,
    sellingprice  float(17,2) default NULL,
  description longtext     default NULL,
  comments    longtext     default NULL,
  additional  longtext     default NULL,
  createdate  datetime NOT NULL default '0000-00-00 00:00:00',
  modifydate  datetime NOT NULL default '0000-00-00 00:00:00',
  lastqcheck  datetime default NULL,
  createuser  bigint(20) NOT NULL default '0',
  modifyuser  bigint(20) NOT NULL default '0',
  editor      varchar(100) NOT NULL default '',
  realeditor  varchar(100) NOT NULL default '',
  srcsys      varchar(100) default 'w5base',
  srcid       varchar(20) default NULL,
  srcload     datetime    default NULL,
  PRIMARY KEY  (id),
  UNIQUE KEY srcsys (srcsys,srcid),
  KEY name (name),
  UNIQUE KEY shortname (shortname),
  UNIQUE KEY namegroup (articlegroup,name),
  KEY qcheck (lastqcheck)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
